nameOverride: ""
fullnameOverride: ""

extraFileMappings: {}

configs:
  swift_upload.py: |
    #!/usr/bin/env python3

    import sys
    import argparse

    from cloudbridge.factory import CloudProviderFactory
    from cloudbridge.factory import ProviderList

    provider = CloudProviderFactory().create_provider(ProviderList.OPENSTACK, {})

    def main(arguments):

        parser = argparse.ArgumentParser(
            description=__doc__,
            formatter_class=argparse.RawDescriptionHelpFormatter)
        parser.add_argument('filepath', help="File to upload", type=str)
        parser.add_argument('destination', help="Destination in bucket", type=str)
        parser.add_argument('-b', '--bucket', help="Name of destination bucket", type=str)

        args = parser.parse_args(arguments)

        bucket = provider.storage.buckets.get(args.bucket)
        ob = bucket.objects.create(args.destination)

        uploaded = False

        while not uploaded:
            uploaded = ob.upload_from_file(args.filepath)
        print(f'Uploaded: {args.filepath} of size {ob.size} bytes')

    if __name__ == '__main__':
        sys.exit(main(sys.argv[1:]))

  upload_package.sh: |
    #!/bin/bash
    set -x
    mkdir -p "~/$(dirname $1)";
    BASE_URL="http://bioconductor.unipi.it/packages";
    cd "~/$(dirname $1)" && curl -O "$BASE_URL/$1" && ls -lh . && echo $(pwd) && python /mnt/configs/swift_upload.py -b "packages" "$(basename $1)" "/$1";

cloneJob:
  image: almahmoud/cloudbridge:3.9-test
  command: cat /mnt/configs/list.txt | xargs -I@ bash /mnt/configs/upload_package.sh @
  extraEnv: []
